run:
  tests: true

linters:
  enable-all: true
  disable:
    - gomnd
    - exhaustivestruct
    - testpackage
    - godox
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - forbidigo
        - errorlint
